apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-114441256
  namespace: migrate-114441256
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "MigrateDemo2026!"
  MYSQL_DATABASE: "appdb"
  MYSQL_USER: "appuser"
  MYSQL_PASSWORD: "MigrateDemo2026!"
