apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-114441256
  namespace: migrate-114441256
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
