apiVersion: v1
kind: Service
metadata:
  name: app-114441256
  namespace: migrate-114441256
  labels:
    app: app-114441256
spec:
  type: NodePort
  selector:
    app: app-114441256
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
