apiVersion: v1
kind: Service
metadata:
  name: db-114441256
  namespace: migrate-114441256
  labels:
    app: db-114441256
spec:
  type: ClusterIP
  selector:
    app: db-114441256
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
    protocol: TCP
